#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "piefed"
name = "PieFed"

description.en = "Federated forum and link aggregator, for your community"
description.fr = "Forum and aggrégateur de liens fédéré, pour votre communauté"

version = "1.3.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "AGPL-3.0-only"
website = "https://join.piefed.social/"
demo = "https://piefed.social/"
admindoc = "https://join.piefed.social/docs/admin-guide/"
userdoc = "https://join.piefed.social/docs/"
code = "https://codeberg.org/rimu/pyfedi"

[integration]
yunohost = '>= 12.0'
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = true
sso = false
disk = "500M"
ram.build = "50M"
ram.runtime = "3G"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://codeberg.org/rimu/pyfedi/archive/v1.3.0.tar.gz"
        sha256 = "80408af01a56b062d844983303d6cb27be5abdf589caa136ed3b910d366ed040"
        autoupdate.strategy = "latest_forgejo_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.exposed = false
    notifs.exposed = false

    [resources.apt]
    packages = "postgresql libpq-dev redis-server python3-psycopg2 tesseract-ocr python3 python3-venv"

    [resources.database]
    type = "postgresql"
